# Generated by Django 3.2.25 on 2024-10-04 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import ticketing.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date_time', models.DateTimeField(default=django.utils.timezone.localtime)),
            ],
        ),
        migrations.CreateModel(
            name='RequestEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram', models.IntegerField(default=2)),
                ('has_internet', models.BooleanField(default=False)),
                ('other_config', models.TextField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('FOR REVISION', 'For Revision'), ('PROCESSING', 'Processing'), ('ACCEPTED', 'Accepted'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('DELETED', 'Deleted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('cores', models.IntegerField(default=1)),
                ('request_date', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('date_needed', models.DateField(default=ticketing.models.expiration_date_default)),
                ('expired_date', models.DateField(default=None, null=True)),
                ('expiration_date', models.DateField(null=True)),
                ('ongoing_date', models.DateTimeField(default=None, null=True)),
                ('vm_date_tested', models.DateTimeField(default=None, null=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_entries', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='requested_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequestUseCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_use_case', models.CharField(choices=[('CLASS COURSE', 'Course'), ('RESEARCH', 'Research'), ('THESIS', 'Thesis'), ('TEST', 'Test')], max_length=45)),
                ('vm_count', models.IntegerField(default=1)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.requestentry')),
            ],
        ),
        migrations.CreateModel(
            name='RequestEntryAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_date', models.DateTimeField(auto_now_add=True)),
                ('changes', models.TextField()),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('request_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='ticketing.requestentry')),
            ],
        ),
        migrations.CreateModel(
            name='PortRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(max_length=45)),
                ('dest_ports', models.CharField(max_length=45)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.requestentry')),
            ],
        ),
        migrations.CreateModel(
            name='IssueTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=10000)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('resolve_date', models.DateTimeField(null=True)),
                ('category', models.CharField(choices=[('System Username', 'System Username'), ('System Password', 'System Password'), ('Virtual Machine Connection', 'Vm Connection'), ('Installation Issues', 'Installation Issues'), ('Request for Extension', 'Request For Extension'), ('Delete Request', 'Delete Request'), ('Additional Installation / Modification', 'Additional'), ('General Problems', 'Others')], max_length=100)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.requestentry')),
            ],
        ),
        migrations.CreateModel(
            name='IssueFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='issue_files/')),
                ('uploaded_date', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.issueticket')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IssueCommentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='issue_files/comments/')),
                ('uploaded_date', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.issuecomment')),
            ],
        ),
        migrations.AddField(
            model_name='issuecomment',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.issueticket'),
        ),
        migrations.AddField(
            model_name='issuecomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date_time', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('request_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.requestentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('id', 'request_entry')},
            },
        ),
    ]
