# Generated by Django 5.0.4 on 2024-05-03 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_id', models.CharField(max_length=30)),
                ('template_id', models.CharField(max_length=30)),
                ('cores', models.IntegerField(default=1)),
                ('ram', models.IntegerField(default=2)),
                ('has_internet', models.BooleanField(default=False)),
            ],
        ),
    ]
