# Generated by Django 3.2.25 on 2024-07-08 05:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import ticketing.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram', models.IntegerField(default=2)),
                ('has_internet', models.BooleanField(default=False)),
                ('other_config', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('FOR REVISION', 'For Revision'), ('PROCESSING', 'Processing'), ('ACCEPTED', 'Accepted'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('DELETED', 'Deleted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('cores', models.IntegerField(default=1)),
                ('isExpired', models.BooleanField(default=False)),
                ('requestDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_needed', models.DateField(default=ticketing.models.expiration_date_default)),
                ('expiration_date', models.DateField(default=ticketing.models.date_needed_default)),
                ('is_vm_tested', models.BooleanField(default=False)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_entries', to=settings.AUTH_USER_MODEL)),
                ('fulfilled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilled_entries', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='requested_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VMTemplates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vm_id', models.CharField(max_length=45)),
                ('vm_name', models.CharField(max_length=90)),
                ('cores', models.IntegerField()),
                ('ram', models.IntegerField()),
                ('storage', models.IntegerField()),
                ('node', models.CharField(max_length=45)),
                ('is_lxc', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('admin', 'Admin')], default='student', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequestUseCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_use_case', models.CharField(default='CLASS_COURSE', max_length=45, null=True)),
                ('vm_count', models.IntegerField(default=1, null=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.requestentry')),
            ],
        ),
        migrations.CreateModel(
            name='RequestEntryAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_date', models.DateTimeField(auto_now_add=True)),
                ('changes', models.TextField()),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('request_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='ticketing.requestentry')),
            ],
        ),
        migrations.AddField(
            model_name='requestentry',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ticketing.vmtemplates'),
        ),
        migrations.CreateModel(
            name='PortRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(blank=True, max_length=45, null=True)),
                ('dest_ports', models.CharField(blank=True, max_length=45, null=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.requestentry')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('request_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.requestentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('id', 'request_entry')},
            },
        ),
    ]
