# Generated by Django 3.2.25 on 2024-07-07 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestentry',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('FOR_REVISION', 'FOR REVISION'), ('PROCESSING', 'PROCESSING'), ('ONGOING', 'ONGOING'), ('COMPLETED', 'COMPLETED'), ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED'), ('DELETED', 'DELETED')], default='PENDING', max_length=20),
        ),
    ]
