# Generated by Django 5.0.6 on 2024-05-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OSList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os_code', models.CharField(max_length=45)),
                ('os_name', models.CharField(max_length=90)),
            ],
            options={
                'db_table': 'os_list',
            },
        ),
    ]
