# Generated by Django 3.2.25 on 2024-06-27 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VMTemplates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vm_id', models.CharField(max_length=45)),
                ('vm_name', models.CharField(max_length=90)),
                ('cores', models.IntegerField()),
                ('ram', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='requestentry',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticketing.vmtemplates'),
        ),
    ]
