# Generated by Django 5.0.6 on 2024-05-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('tsg', 'TSG')], default='student', max_length=20),
        ),
    ]
