# Generated by Django 3.2.25 on 2024-07-02 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vmtemplates',
            name='is_lxc',
            field=models.BooleanField(default=False),
        ),
    ]
