# Generated by Django 5.0.4 on 2024-05-03 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0002_requestentry_storage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestentry',
            name='storage',
        ),
    ]
