# Generated by Django 5.0.6 on 2024-05-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0002_oslist'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestentry',
            name='other_config',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestentry',
            name='use_case',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
