# Generated by Django 5.0.6 on 2024-05-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0003_requestentry_other_config_requestentry_use_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestentry',
            name='vm_count',
            field=models.IntegerField(default=1),
        ),
    ]
