# Generated by Django 5.0.6 on 2024-05-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0003_vmtemplates_alter_requestentry_requester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestentry',
            name='status',
            field=models.CharField(choices=[('P', 'PENDING'), ('FR', 'FOR REVISION'), ('CR', 'CREATING'), ('CO', 'COMPLETED'), ('RJ', 'REJECTED'), ('D', 'DELETED')], default='P', max_length=10),
        ),
        migrations.AlterField(
            model_name='requestentry',
            name='storage',
            field=models.FloatField(default=0),
        ),
    ]
