# Generated by Django 5.0.4 on 2024-05-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0003_remove_requestentry_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestentry',
            name='storage',
            field=models.FloatField(default=2.0),
        ),
    ]
