# Generated by Django 5.0.6 on 2024-05-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0004_requestentry_vm_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestentry',
            name='assigned_to',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
