# Generated by Django 5.0.6 on 2024-05-30 14:55

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0005_requestentry_expirationdate_requestentry_fulfilledby_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestentry',
            old_name='expirationDate',
            new_name='expiration_date',
        ),
        migrations.AddField(
            model_name='requestentry',
            name='date_needed',
            field=models.DateField(default=datetime.date(2024, 6, 2)),
        ),
        migrations.AlterField(
            model_name='requestentry',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
