# Generated by Django 5.0.6 on 2024-05-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0005_requestentry_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestentry',
            name='revision_comments',
            field=models.TextField(default=' '),
        ),
    ]
