# Generated by Django 5.0.6 on 2024-06-03 06:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0006_rename_expirationdate_requestentry_expiration_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=45)),
                ('section', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='PortRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface', models.CharField(max_length=30)),
                ('protocol', models.CharField(max_length=45)),
                ('source_address', models.CharField(max_length=45)),
                ('source_ports', models.CharField(max_length=45)),
                ('dest_address', models.CharField(max_length=45)),
                ('dest_ports', models.CharField(max_length=45)),
                ('nat_ip', models.CharField(max_length=45)),
                ('nat_ports', models.CharField(max_length=45)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='requestentry',
            name='date_needed',
            field=models.DateField(default=datetime.date(2024, 6, 6)),
        ),
        migrations.AlterField(
            model_name='requestentry',
            name='expiration_date',
            field=models.DateField(default=datetime.date(2024, 9, 1)),
        ),
        migrations.AlterField(
            model_name='requestentry',
            name='use_case',
            field=models.CharField(choices=[('THESIS', 'Thesis'), ('RESEARCH', 'Research'), ('TEST', 'Test'), ('CLASS_COURSE', 'Class Course')], default='CLASS_COURSE', max_length=20),
        ),
    ]
