# Generated by Django 5.0.6 on 2024-05-22 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0007_alter_requestentry_revision_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestentry',
            name='template_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.oslist'),
        ),
    ]
