# Generated by Django 5.0.6 on 2024-06-04 07:01

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0007_classcode_portrules_alter_requestentry_date_needed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_number', models.IntegerField(default=1)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequestUseCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_use_case', models.CharField(default='CLASS_COURSE', max_length=45, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ClassCode',
        ),
        migrations.RemoveField(
            model_name='requestentry',
            name='use_case',
        ),
        migrations.AlterField(
            model_name='requestentry',
            name='date_needed',
            field=models.DateField(default=datetime.date(2024, 6, 7)),
        ),
        migrations.AlterField(
            model_name='requestentry',
            name='expiration_date',
            field=models.DateField(default=datetime.date(2024, 9, 2)),
        ),
        migrations.AddField(
            model_name='requestusecase',
            name='reqeust',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.requestentry'),
        ),
        migrations.AddField(
            model_name='grouplist',
            name='request_use_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.requestusecase'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='request_use_case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticketing.requestusecase'),
        ),
    ]
