# Generated by Django 5.0.6 on 2024-06-04 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0008_grouplist_requestusecase_delete_classcode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestusecase',
            old_name='reqeust',
            new_name='request',
        ),
    ]
