# Generated by Django 5.0.6 on 2024-06-04 16:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0009_rename_reqeust_requestusecase_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestentry',
            name='date_needed',
            field=models.DateField(default=datetime.date(2024, 6, 8)),
        ),
        migrations.AlterField(
            model_name='requestentry',
            name='expiration_date',
            field=models.DateField(default=datetime.date(2024, 9, 3)),
        ),
        migrations.AlterField(
            model_name='requestentry',
            name='status',
            field=models.CharField(choices=[('P', 'PENDING'), ('FR', 'FOR REVISION'), ('PRCS', 'PROCESSING'), ('OG', 'ONGOING'), ('CO', 'COMPLETED'), ('RJ', 'REJECTED'), ('D', 'DELETED')], default='P', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('admin', 'Admin')], default='student', max_length=20),
        ),
    ]
