# Generated by Django 5.0.6 on 2024-05-28 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0010_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestentry',
            name='revision_comments',
        ),
    ]
