# Generated by Django 5.0.6 on 2024-06-05 13:22

import ticketing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0010_alter_requestentry_date_needed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestentry',
            old_name='fulfilledBy',
            new_name='fulfilled_by',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='request_use_case',
        ),
        migrations.AlterField(
            model_name='requestentry',
            name='date_needed',
            field=models.DateField(default=ticketing.models.date_needed_default),
        ),
        migrations.AlterField(
            model_name='requestentry',
            name='expiration_date',
            field=models.DateField(default=ticketing.models.expiration_date_default),
        ),
        migrations.AlterField(
            model_name='requestentry',
            name='isExpired',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='requestentry',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('FOR_REVISION', 'FOR REVISION'), ('PROCESSING', 'PROCESSING'), ('ONGOING', 'ONGOING'), ('COMPLETED', 'COMPLETED'), ('REJECTED', 'REJECTED'), ('DELETED', 'DELETED')], default='PENDING', max_length=20),
        ),
    ]
