# Generated by Django 5.0.6 on 2024-06-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0011_rename_fulfilledby_requestentry_fulfilled_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestentry',
            name='storage',
        ),
        migrations.AlterField(
            model_name='grouplist',
            name='user',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
