# Generated by Django 5.0.6 on 2024-06-24 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0013_requestentryaudit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portrules',
            name='dest_address',
        ),
        migrations.RemoveField(
            model_name='portrules',
            name='interface',
        ),
        migrations.RemoveField(
            model_name='portrules',
            name='nat_ip',
        ),
        migrations.RemoveField(
            model_name='portrules',
            name='nat_ports',
        ),
        migrations.RemoveField(
            model_name='portrules',
            name='protocol',
        ),
        migrations.RemoveField(
            model_name='portrules',
            name='source_address',
        ),
        migrations.RemoveField(
            model_name='portrules',
            name='source_ports',
        ),
        migrations.RemoveField(
            model_name='requestentry',
            name='vm_count',
        ),
        migrations.AddField(
            model_name='requestusecase',
            name='vm_count',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.DeleteModel(
            name='GroupList',
        ),
    ]
