# Generated by Django 5.0.6 on 2024-06-24 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0014_remove_portrules_dest_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portrules',
            name='protocol',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='portrules',
            name='request',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ticketing.requestentry'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portrules',
            name='dest_ports',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
