---
- name: Resize disk and file system
  hosts: all
  become: yes
  tasks:
    - name: Ensure parted is installed
      apt:
        name: parted
        state: present

    - name: Print current partition table
      command: fdisk -l /dev/sda
      register: fdisk_output
      ignore_errors: yes

    - name: Print current partition table to logs
      debug:
        var: fdisk_output.stdout_lines

    - name: Use fdisk to delete and recreate the partition
      expect:
        command: fdisk /dev/sda
        responses:
          'Command (m for help):': 'p\n'
          'Command (m for help):': 'd\n'
          'Partition number (1, 2, default 2):': '2\n'
          'Command (m for help):': 'n\n'
          'Select (default p):': 'p\n'
          'Partition number (2-4, default 2):': '2\n'
          'First sector': '\n'
          'Last sector, +sectors or +size{K,M,G,T,P} (2048-104857599, default 104857599):': '\n'
          'Do you want to remove the signature? [Y]es/[N]o:': 'N\n'
          'Command (m for help):': 'w\n'
        timeout: 60

    - name: Resize the filesystem
      command: resize2fs /dev/sda2

    - name: Print the new disk usage
      command: df -h
      register: disk_usage

    - name: Print new disk usage to logs
      debug:
        var: disk_usage.stdout_lines
