- name: Resize Proxmox VM disk and filesystem
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Resize the filesystem (ext4)
      shell: sudo resize2fs /dev/sda1
      become: yes
      become_method: sudo
      delegate_to: "{{ vm_ip }}"
      vars:
        ansible_ssh_user: "{{ vm_user }}"
        ansible_ssh_private_key_file: ~/.ssh/id_rsa
