---
- name: Rename user and update password on Linux VM
  hosts: all
  become: yes
  vars:
    old_username: "olduser"
    new_username: "newuser"
    new_password: "newpassword"
  tasks:
    - name: Ensure the old user exists
      user:
        name: "{{ old_username }}"
        state: present

    - name: Rename the old user to new user
      command: usermod -l {{ new_username }} -d /home/{{ new_username }} -m {{ old_username }}
      when: old_username != new_username

    - name: Ensure the new user's home directory is correct
      file:
        path: "/home/{{ new_username }}"
        state: directory
        owner: "{{ new_username }}"
        group: "{{ new_username }}"
        recurse: yes

    - name: Update the new user's password
      user:
        name: "{{ new_username }}"
        password: "{{ new_password | password_hash('sha512') }}"

    - name: Update sudoers if necessary (optional)
      lineinfile:
        path: /etc/sudoers
        regexp: '^{{ old_username }}'
        line: '{{ new_username }} ALL=(ALL) NOPASSWD:ALL'
        state: present
      when: old_username != new_username
