---
- name: Resize disk and file system
  hosts: all
  become: yes
  tasks:
    - name: Ensure parted is installed
      apt:
        name: parted
        state: present

    - name: Print current partition table
      command: fdisk -l /dev/sda
      register: fdisk_output
      ignore_errors: yes

    - name: Print current partition table to logs
      debug:
        var: fdisk_output.stdout_lines

    - name: Delete partition /dev/sda2
      parted:
        device: /dev/sda
        number: 2
        state: absent

    - name: Create new primary partition on /dev/sda
      parted:
        device: /dev/sda
        number: 2
        part_start: 0%
        part_end: 100%
        fs_type: ext4
        state: present

    - name: Resize the filesystem
      command: resize2fs /dev/sda2

    - name: Print the new disk usage
      command: df -h
      register: disk_usage

    - name: Print new disk usage to logs
      debug:
        var: disk_usage.stdout_lines
