# Generated by Django 3.2.25 on 2024-06-28 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proxmox', '0001_initial'),
        ('guacamole', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guacamoleconnection',
            name='vm',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='proxmox.virtualmachines'),
        ),
    ]
