# Generated by Django 3.2.25 on 2024-06-28 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guacamole', '0002_guacamoleconnection_vm'),
    ]

    operations = [
        migrations.AddField(
            model_name='guacamoleconnection',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('DELETED', 'Deleted')], default='ACTIVE', max_length=20),
        ),
    ]
