# Generated by Django 3.2.25 on 2024-07-07 07:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proxmox', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(max_length=45)),
                ('source_port', models.CharField(max_length=45)),
                ('dest_port', models.CharField(max_length=45)),
                ('rule_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('is_disabled', models.BooleanField(default=False)),
                ('vm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proxmox.virtualmachines')),
            ],
        ),
    ]
