# Generated by Django 3.2.25 on 2024-10-04 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='VMTemplates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vm_id', models.CharField(max_length=45)),
                ('vm_name', models.CharField(max_length=90)),
                ('cores', models.IntegerField()),
                ('ram', models.IntegerField()),
                ('storage', models.IntegerField()),
                ('node', models.CharField(max_length=45)),
                ('is_lxc', models.BooleanField(default=False)),
                ('guacamole_protocol', models.CharField(choices=[('rdp', 'Rdp'), ('vnc', 'Vnc'), ('ssh', 'Ssh')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='VirtualMachines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vm_id', models.IntegerField()),
                ('vm_name', models.CharField(max_length=90)),
                ('cores', models.IntegerField()),
                ('ram', models.IntegerField()),
                ('storage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ip_add', models.CharField(default=None, max_length=15, null=True)),
                ('is_lxc', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('CREATING', 'Creating'), ('ACTIVE', 'Active'), ('SHUTDOWN', 'Shutdown'), ('DESTROYED', 'Destroyed')], default='CREATING', max_length=20)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proxmox.nodes')),
            ],
        ),
    ]
