# Generated by Django 3.2.25 on 2024-07-08 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ticketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='VirtualMachines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vm_id', models.IntegerField()),
                ('vm_name', models.CharField(max_length=90)),
                ('cores', models.IntegerField()),
                ('ram', models.IntegerField()),
                ('storage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ip_add', models.CharField(max_length=15)),
                ('is_lxc', models.BooleanField(default=False)),
                ('vm_password', models.CharField(default='DLSU1234!', max_length=45)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SHUTDOWN', 'Shutdown'), ('DESTROYED', 'Destroyed')], default='ACTIVE', max_length=20)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proxmox.nodes')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ticketing.requestentry')),
            ],
        ),
    ]
