# Generated by Django 3.2.25 on 2024-06-27 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0002_auto_20240627_1428'),
        ('proxmox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmachines',
            name='request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticketing.requestentry'),
        ),
        migrations.DeleteModel(
            name='VMTemplates',
        ),
    ]
