# Generated by Django 3.2.25 on 2024-08-22 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proxmox', '0001_initial'),
        ('ticketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationPorts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dest_port', models.IntegerField()),
                ('port_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.portrules')),
                ('vm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='proxmox.virtualmachines')),
            ],
        ),
    ]
